//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 3/1/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//


import UIKit

public class StyleKitName: NSObject {

    //// Drawing Methods

    public class func drawCanvas1() {
        //// Color Declarations
        let color = UIColor(red: 0.815, green: 0.091, blue: 0.091, alpha: 1.000)

        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(60, 30, 55, 56))
        color.setFill()
        ovalPath.fill()
        UIColor.blackColor().setStroke()
        ovalPath.lineWidth = 1
        ovalPath.stroke()
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
