platform :ios, '8.0'
use_frameworks!

pod 'UIColor+BFPaperColors', '~> 1.3.1'
pod 'BFPaperCollectionViewCell', '~> 2.1.2'
pod 'MQTTKit', '~> 0.1'
pod 'SVProgressHUD', '~> 1.1'
pod 'CCMPopup'
pod 'WYPopoverController', '~> 0.2.2'
#pod 'SwiftEventBus', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
pod 'Alamofire', :git => 'https://github.com/winzig/Alamofire.git', :branch => 'xcode-6.3'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode6.3'
#pod 'Alamofire-SwiftyJSON',  :git => 'https://github.com/SwiftyJSON/Alamofire-SwiftyJSON.git'
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-1.2'
pod 'Async', :git => 'https://github.com/duemunk/Async.git', :branch => 'feature/Swift_1.2'